# Generated by Django 3.2 on 2022-06-28 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('persona_tier', models.IntegerField(choices=[(1, 'Tier 1 Minister | DG | CEO | Chief Register'), (2, 'Tier 2 Permanent Sec'), (3, 'Tier 3 Director'), (4, 'Tier 4 Deputy Director'), (5, 'Tier 5 Assistant Duputy Director'), (6, 'Tier 6 Clerical Officer'), (7, 'Tier 7 Protocol Oficer'), (8, 'Tier 8 ICT Oficers'), (9, 'Tier 9 Registry Officer'), (10, 'Tier 10 OTher User')])),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic_url', models.CharField(default=0, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userpersona')),
            ],
        ),
    ]
