# Generated by Django 3.2 on 2022-12-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersona',
            name='persona_tier',
            field=models.IntegerField(choices=[(1, 'Tier 1 Minister | DG | CEO | Chief Register'), (2, 'Tier 2 Permanent Sec | VC'), (3, 'Tier 3 Director'), (4, 'Tier 4 Deputy Director'), (5, 'Tier 5 Assistant Duputy Director'), (6, 'Tier 6 Clerical Officer'), (7, 'Tier 7 Protocol Oficer'), (8, 'Tier 8 ICT Oficers'), (9, 'Tier 9 Registry Officer'), (10, 'Tier 10 OTher User')]),
        ),
    ]
