# Generated by Django 4.0.2 on 2023-06-18 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_contractors_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruser_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruser_persona', to='accounts.userpersona'),
        ),
        migrations.AlterField(
            model_name='contractors',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contractors',
            name='company_name',
            field=models.CharField(default='default: company name', max_length=20),
        ),
    ]
