# Generated by Django 3.2 on 2023-07-13 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_user_alter_account_user_persona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractors',
            name='status',
            field=models.CharField(choices=[('verified', 'verified'), ('pending', 'pending')], default='pending', max_length=50),
        ),
    ]
