# Generated by Django 3.2 on 2023-02-16 05:58

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230216_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institutions',
            name='template',
        ),
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('B.SC', 'B.Sc'), ('HND', 'HND'), ('M.Sc', 'M.Sc'), ('PGD', 'PGD'), ('PHD', 'PGD'), ('Dip', 'Dip'), ('NCE', 'NCE')], max_length=100)),
                ('fee', models.IntegerField(blank=True)),
                ('template', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('institutions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.institutions')),
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='applicationtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.applicationtype'),
            preserve_default=False,
        ),
    ]
