# Generated by Django 3.2 on 2023-02-16 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20230216_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtype',
            name='institutions',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.institutions'),
        ),
    ]
