# Generated by Django 3.2 on 2023-07-13 18:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_contractors_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('verified', 'verified'), ('pending', 'pending')], default='pending', max_length=50)),
                ('file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['txt', 'pdf'])])),
            ],
            options={
                'verbose_name': 'ContractorDocument',
                'verbose_name_plural': 'ContractorDocuments',
            },
        ),
        migrations.AddField(
            model_name='contractors',
            name='documents',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_documents', to='accounts.contractordocument'),
        ),
    ]
