# Generated by Django 3.2 on 2023-07-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230713_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractors',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractor_account', to='accounts.account'),
        ),
    ]
