# Generated by Django 3.2 on 2023-07-26 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20230726_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractors',
            name='documents',
        ),
    ]
