# Generated by Django 3.2 on 2023-07-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_contractors_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractors',
            name='category',
            field=models.CharField(choices=[('Software', 'Software'), ('Telecommunication', 'Telecommunication'), ('Construction', 'Construction'), ('others', 'others')], default='Software', max_length=50),
        ),
    ]
