# Generated by Django 3.2 on 2023-08-06 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_contractors_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractordocument',
            name='status',
        ),
        migrations.AddField(
            model_name='contractordocument',
            name='contractor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_document', to='accounts.contractors'),
        ),
    ]
