# Generated by Django 3.2 on 2024-02-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersona',
            name='persona_tier',
            field=models.IntegerField(choices=[(1, 'Tier 1 Minister | DG | CEO | Chief Register'), (2, 'Tier 2 Permanent Sec | VC'), (3, 'Tier 3 Director'), (4, 'Tier 4 Deputy Director'), (5, 'Tier 5 Assistant Duputy Director'), (6, 'Tier 6 Clerical Officer'), (7, 'Tier 7 Protocol Oficer'), (8, 'Tier 8 Other'), (9, 'Tier 9 Registry Officer'), (10, 'Tier 10 ICT Personal'), (11, 'Tier 11 Contractors'), (12, 'Tier 12 Procurement Officer')]),
        ),
    ]
