# Generated by Django 3.2 on 2023-01-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_correspondance_to_registry_first', models.BooleanField(default=True)),
            ],
        ),
    ]
