# Generated by Django 3.2 on 2023-02-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('Department', 'Department')], max_length=100),
        ),
    ]
