# Generated by Django 3.2 on 2022-06-28 10:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('agenda', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('schedule_for', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=1000, null=True)),
                ('scheduled', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('notes', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('paticipants', models.ManyToManyField(related_name='paticipant', to='accounts.Account')),
                ('schedulers', models.ManyToManyField(to='accounts.Account')),
            ],
        ),
    ]
