# Generated by Django 3.2 on 2023-04-28 10:32

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule_Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_on', models.DateField(blank=True, null=True)),
                ('end_on', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, choices=[('online', 'Online'), ('physical', 'Physical')], max_length=1000, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('draft', models.BooleanField(default=False)),
                ('minutes_of_meeting', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('done', models.BooleanField(default=False)),
                ('attachment', models.FilePathField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('paticipants', models.ManyToManyField(related_name='paticipant', to='accounts.Account')),
                ('scheduled_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=100)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.schedule_meeting')),
            ],
        ),
    ]
