# Generated by Django 3.2 on 2024-01-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_meeting',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='schedule_meeting',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
