# Generated by Django 3.2 on 2023-01-03 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userpersona_persona_tier'),
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule_meeting',
            old_name='scheduled',
            new_name='draft',
        ),
        migrations.RenameField(
            model_name='schedule_meeting',
            old_name='schedule_for',
            new_name='end_on',
        ),
        migrations.RenameField(
            model_name='schedule_meeting',
            old_name='notes',
            new_name='minutes_of_meeting',
        ),
        migrations.RemoveField(
            model_name='schedule_meeting',
            name='schedulers',
        ),
        migrations.AddField(
            model_name='schedule_meeting',
            name='attachment',
            field=models.FilePathField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule_meeting',
            name='scheduled_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule_meeting',
            name='start_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OnlineMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api', models.CharField(max_length=100)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.schedule_meeting')),
            ],
        ),
    ]
