# Generated by Django 4.2.11 on 2024-03-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onlinemeeting',
            name='meeting',
        ),
        migrations.RemoveField(
            model_name='schedule_meeting',
            name='paticipants',
        ),
        migrations.RemoveField(
            model_name='schedule_meeting',
            name='scheduled_by',
        ),
        migrations.DeleteModel(
            name='Agenda',
        ),
        migrations.DeleteModel(
            name='OnlineMeeting',
        ),
        migrations.DeleteModel(
            name='Schedule_Meeting',
        ),
    ]
