# Generated by Django 3.2 on 2023-01-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20230103_1616'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule_meeting',
            old_name='agenda',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='schedule_meeting',
            name='end_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule_meeting',
            name='start_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
