# Generated by Django 3.2 on 2024-01-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20240110_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_meeting',
            name='status',
            field=models.CharField(choices=[('up_comming', 'up_comming'), ('previous', 'previous'), ('all', 'all')], default='all', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule_meeting',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='meeting_files/'),
        ),
        migrations.AlterField(
            model_name='schedule_meeting',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
