# Generated by Django 3.2 on 2024-01-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20240115_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_meeting',
            name='status',
            field=models.CharField(choices=[('up_comming', 'up_comming'), ('previous', 'previous'), ('all', 'all')], default='all', max_length=100),
        ),
    ]
