# Generated by Django 3.2 on 2023-01-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_auto_20230103_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_meeting',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule_meeting',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
