# Generated by Django 3.2 on 2024-03-17 13:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_alter_schedule_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule_meeting',
            name='agenda',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
