# Generated by Django 3.2 on 2023-01-10 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_auto_20230103_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_meeting',
            name='venue',
            field=models.CharField(blank=True, choices=[('online', 'Online'), ('physical', 'Physical')], max_length=1000, null=True),
        ),
    ]
