# Generated by Django 3.2 on 2024-03-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_schedule_meeting_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule_meeting',
            name='attachment',
            field=models.ImageField(blank=True, null=True, upload_to='meetingfiles/'),
        ),
    ]
