# Generated by Django 4.2.11 on 2024-03-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0007_auto_20240318_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
