# Generated by Django 3.2 on 2023-02-15 15:17

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('unique_identifier', models.CharField(max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('draft', models.BooleanField(default=True)),
                ('archive', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('stared', models.BooleanField(default=False)),
                ('created', models.TimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('sender_stage', models.CharField(choices=[('Clearing', 'Clearing'), ('Done', 'Done')], max_length=200)),
                ('reciever_stage', models.CharField(blank=True, choices=[('Clearing', 'Clearing'), ('Protocol', 'Protocol'), ('Done', 'Done')], max_length=200, null=True)),
                ('send', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondance.folder')),
                ('forwarded_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='accounts.account')),
                ('initiated_unit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_unit', to='home.unit')),
                ('intended_unit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.unit')),
                ('send_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='accounts.account')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Folder_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondance.folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='file/')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('folder_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correspondance.folder_content')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('visible', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-timestamp', '-updated'],
            },
        ),
    ]
