# Generated by Django 3.2 on 2022-06-28 10:26

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('unique_identifier', models.CharField(max_length=8)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('draft', models.BooleanField(default=True)),
                ('archive', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.BooleanField(default=False)),
                ('stared', models.BooleanField(default=False)),
                ('created', models.TimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('sender_stage', models.CharField(choices=[('Clearing', 'Clearing'), ('Done', 'Done')], max_length=200)),
                ('reciever_stage', models.CharField(blank=True, choices=[('Clearing', 'Clearing'), ('Protocol', 'Protocol'), ('Done', 'Done')], max_length=200, null=True)),
                ('send', models.BooleanField(default=False)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondance.folder')),
                ('forwarded_by', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='accounts.account')),
                ('send_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Folder_Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correspondance.folder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(upload_to='file/')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('folder_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='correspondance.folder_content')),
            ],
        ),
    ]
