# Generated by Django 3.2 on 2023-01-10 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('correspondance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='intended_unit',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='home.unit'),
            preserve_default=False,
        ),
    ]
