# Generated by Django 3.2 on 2024-01-15 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='media',
            field=models.ImageField(upload_to='memo_file/'),
        ),
    ]
