# Generated by Django 3.2 on 2023-01-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('correspondance', '0002_routing_intended_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='initiated_unit',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='initiated_unit', to='home.unit'),
            preserve_default=False,
        ),
    ]
