# Generated by Django 3.2 on 2024-02-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondance', '0002_alter_file_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routing',
            name='sender_stage',
            field=models.CharField(blank=True, choices=[('Clearing', 'Clearing'), ('Done', 'Done')], max_length=200, null=True),
        ),
    ]
