# Generated by Django 3.2 on 2024-02-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondance', '0006_alter_routing_sender_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routing',
            name='sender_stage',
            field=models.CharField(choices=[('Done', 'Done'), ('Clearing', 'Clearing')], default='Done', max_length=200),
        ),
    ]
