# Generated by Django 4.0.2 on 2023-06-18 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_account_user_alter_account_user_persona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='contract title', max_length=20)),
                ('category', models.CharField(choices=[('open tender', 'open tender'), ('selective tendder', 'selective tender'), ('all', 'all')], help_text='broadcast range', max_length=20)),
                ('responsibilty', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('tender_type', models.CharField(choices=[('open tender', 'open tender'), ('selective tendder', 'selective tender'), ('all', 'all')], help_text='audience', max_length=20)),
                ('description', models.CharField(default='details of project', max_length=30)),
                ('budget', models.CharField(max_length=20)),
                ('priority', models.IntegerField(choices=[('1', 'HIGH'), ('2', 'MEDIUM'), ('3', 'LOW')], default='3', max_length=20)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contractors', to='accounts.contractors')),
            ],
        ),
    ]
