# Generated by Django 4.0.2 on 2023-06-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precurement',
            name='priority',
            field=models.IntegerField(choices=[('1', 'HIGH'), ('2', 'MEDIUM'), ('3', 'LOW')], default='3'),
        ),
    ]
