# Generated by Django 3.2 on 2023-07-20 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20230713_1841'),
        ('procurement', '0003_alter_precurement_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precurement',
            name='category',
            field=models.CharField(choices=[('open tender', 'open tender'), ('selective tender', 'selective tender'), ('all', 'all')], help_text='broadcast range', max_length=20),
        ),
        migrations.AlterField(
            model_name='precurement',
            name='contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_contractors', to='accounts.contractors'),
        ),
        migrations.AlterField(
            model_name='precurement',
            name='priority',
            field=models.IntegerField(choices=[('HIGHEST', 'HIGHEST'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('LOWEST', 'LOWEST')], default=3),
        ),
        migrations.AlterField(
            model_name='precurement',
            name='tender_type',
            field=models.CharField(choices=[('open tender', 'open tender'), ('selective tender', 'selective tender'), ('all', 'all')], help_text='audience', max_length=20),
        ),
    ]
