# Generated by Django 3.2 on 2023-07-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_auto_20230720_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precurement',
            name='priority',
            field=models.CharField(choices=[('HIGHEST', 'HIGHEST'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW'), ('LOWEST', 'LOWEST')], default=3, max_length=20),
        ),
    ]
