# Generated by Django 3.2 on 2023-07-26 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0006_auto_20230721_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precurement_contractors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited', to=settings.AUTH_USER_MODEL)),
                ('precurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisedPrecurement', to='procurement.precurement')),
            ],
            options={
                'verbose_name': 'Precurement_contractors',
                'verbose_name_plural': 'Precurement_contractors',
            },
        ),
    ]