# Generated by Django 3.2 on 2023-07-28 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_alter_precurement_contractor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precurement_contractors',
            name='invite',
        ),
        migrations.RemoveField(
            model_name='precurement_contractors',
            name='precurement',
        ),
        migrations.DeleteModel(
            name='Precurement',
        ),
        migrations.DeleteModel(
            name='Precurement_contractors',
        ),
    ]
