# Generated by Django 3.2 on 2023-12-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0015_alter_precurement_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precurement',
            name='category',
            field=models.CharField(choices=[('Software', 'Software'), ('Telecommunication', 'Telecommunication'), ('Construction', 'Construction'), ('Others', 'Others')], help_text='broadcast range', max_length=20),
        ),
    ]
