# Generated by Django 3.2 on 2023-12-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0017_auto_20231217_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='precurement',
            name='project_file',
            field=models.FileField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
