# Generated by Django 3.2 on 2023-12-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0018_precurement_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precurement',
            name='project_file',
            field=models.ImageField(blank=True, null=True, upload_to='project_files/'),
        ),
    ]
