# Generated by Django 3.2 on 2023-12-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_contractordocument_file'),
        ('procurement', '0019_alter_precurement_project_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procurement_tender_doc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='contractor_tender_doc/')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interested_contractor', to='accounts.contractors')),
                ('precurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement', to='procurement.precurement')),
            ],
            options={
                'verbose_name': 'Procurement_tender_doc',
                'verbose_name_plural': 'Procurement_tender_docs',
            },
        ),
    ]
