# Generated by Django 3.2 on 2024-03-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_account_signature'),
        ('procurement', '0020_procurement_tender_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contractors', models.ManyToManyField(to='accounts.Contractors')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement.precurement')),
            ],
        ),
    ]
