# Generated by Django 3.2 on 2024-03-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0022_contractoraward_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractoraward',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
